"""user add info

Revision ID: 7089f472f9db
Revises: 0443b7c6e56c
Create Date: 2018-05-16 18:09:13.935130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7089f472f9db'
down_revision = '0443b7c6e56c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('info', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'info')
    # ### end Alembic commands ###
